
name: Docker Build and Push
env:
  CURRENT_TAG: V1
  PREV_TAG: None


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.CURRENT_TAG }}
            

      - name: Stopping Old Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ "$(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.PREV_TAG }}")" ]; then
              echo "Stopping Old container"
              docker stop $(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.PREV_TAG }}")
            else
              echo "No container running"
            fi


      - name: Run Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker run -d -p 3000:3000  ${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.CURRENT_TAG }}


      - name: Deleting Old image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.PREV_TAG }} &> /dev/null; then
              echo "Image exists, deleting it..."
              docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/shoes:${{ env.PREV_TAG }}
            else
              echo "Image does not exist."
            fi

            